// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bigCloud': string;
  'bigPokeBall': string;
  'cloud': string;
  'pikachu': string;
  'root': string;
  'smallPokeBall': string;
}
export const cssExports: CssExports;
export default cssExports;
