// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'abilitiesWrap': string;
  'bgWhite': string;
  'contentImg': string;
  'contentStats': string;
  'contentTitle': string;
  'contentWrap': string;
  'hp': string;
  'root': string;
  'stats': string;
  'statsWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
