// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'root': string;
  'subTitle': string;
  'text': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
